### ISSUE TITLE
Decky loader won't build because of broken npm lockfile 

### ISSUE THREAD

**Issue by imadnyc** [Jovian-Experiments/Jovian-NixOS#205]
Enabling `jovian.decky-loader.enable = true` tries to build decky loader, but fails because of the lock file. 

Command run: `sudo nixos-rebuild dry-activate --flake .#nix-deck --show-trace`

```
building the system configuration...
warning: Git tree '/home/dre/Documents/nix-config' is dirty
error: builder for '/nix/store/vfd7b5cy7g4l17xdgg89p29147w6dc9c-decky-loader-frontend-deps-2.10.5.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       >    │                Run "pnpm add -g pnpm" to update.                 │
       >    │                                                                  │
       >    │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
       >    │                                                                  │
       >    ╰──────────────────────────────────────────────────────────────────╯
       > 
       >  ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/decky-frontend-lib/3.21.1' in pnpm-lock.yaml
       >
       > This issue is probably caused by a badly resolved merge conflict.
       > To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
       For full logs, run 'nix log /nix/store/vfd7b5cy7g4l17xdgg89p29147w6dc9c-decky-loader-frontend-deps-2.10.5.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/96g2nx6iy5h61mcr6dbpxvv7svnyiz9z-decky-loader-frontend-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8lqfx57926hw76xq3mnmsqdygrnpm6w0-decky-loader-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cccidg7gm2gvc2achlnb1niab82ay91g-unit-decky-loader.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s2w8wqa2xjf1dxxyz90ydkx1wwdnzsl2-system-units.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-mesa-23.0.3.drv-2': Directory not empty
error: 1 dependencies of derivation '/nix/store/7zfych0d8ns9b4sw0db9cla1048al0w5-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/63pb9abw50kn4cpq5wfqsrcc3bk3lml5-nixos-system-nix-deck-23.05.20231105.aeefe20.drv' failed to build
```

This would probably be fixed just by updating the decky loader lock file, but I don't know where the repo is.

**Comment by imadnyc** [comment]
Updating `pkgs/decky-loader.nix` to use `--no-frozen-lockfile` gets me this error 

```
➜  nix-config git:(master) ✗ sudo nixos-rebuild dry-activate --override-input jovian git+file:///home/dre/Projects/Jovian-NixOS/ --flake .#nix-deck --show-trace
building the system configuration...
warning: Git tree '/home/dre/Documents/nix-config' is dirty
warning: Git tree '/home/dre/Projects/Jovian-NixOS/' is dirty
warning: not writing modified lock file of flake 'git+file:///home/dre/Documents/nix-config':
• Updated input 'jovian':
    'github:Jovian-Experiments/Jovian-NixOS/fd7753956149d4e8b19a810eed445d1a52aecd30' (2023-10-28)
  → 'git+file:///home/dre/Projects/Jovian-NixOS/' (2023-10-28)
error: builder for '/nix/store/i1j0jyrphynzha40vldkac7kxsj4jcwj-decky-loader-frontend-deps-2.10.5.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       >     at Object.parse2 [as parse] (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:114178:15)
       >     at nameVerFromPkgSnapshot (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:114287:28)
       >     at addPreferredVersionsFromLockfile (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:196837:89)
       >     at getPreferredVersionsFromLockfileAndManifests (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:196831:7)
       >     at _installInContext (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:197757:142)
       >     at async installInContext (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:198076:27)
       >     at async _install (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:197622:25)
       >     at async mutateModules (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:197344:23)
       >     at async install (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:197270:45)
       >     at async installDeps (/nix/store/jyr38j4jaglp17n40glf9zdnvhy8km34-pnpm-8.5.1/lib/node_modules/pnpm/dist/pnpm.cjs:199336:31)
       For full logs, run 'nix log /nix/store/i1j0jyrphynzha40vldkac7kxsj4jcwj-decky-loader-frontend-deps-2.10.5.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/hkhj1r3l2yq1aw6f31b3bx0kdp91n9bw-decky-loader-frontend-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r0ls5h1wkqbvw5j16my887nagvs405ic-decky-loader-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w5fgdxq2s0bpb9wqndhipc9638mzxbl4-unit-decky-loader.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zv340agzh27sx8r0isrcnjf793yq45f2-system-units.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-mesa-radv-jupiter-23.3.0.steamos-23.9.1.drv-4/source': Directory not empty
error: 1 dependencies of derivation '/nix/store/f4qy8i32wlqcw1hlrqwpg5vlgldhizlv-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9x6skb8v42kqj21z6y3wyys8nnd27x67-nixos-system-nix-deck-23.05.20231105.aeefe20.drv' failed to build
```

Then, updating the flake.lock to get the newest version of pnpm and adding `pnpm update decky-frontend-lib --latest` before line 34 in `pkgs/decky-loader/default.nix` gets me this, strangely:

```
➜  nix-config git:(master) ✗ sudo nixos-rebuild dry-activate --override-input jovian git+file:///home/dre/Projects/Jovian-NixOS/ --flake .#nix-deck --show-trace
building the system configuration...
warning: Git tree '/home/dre/Documents/nix-config' is dirty
warning: Git tree '/home/dre/Projects/Jovian-NixOS/' is dirty
warning: not writing modified lock file of flake 'git+file:///home/dre/Documents/nix-config':
• Updated input 'jovian':
    'github:Jovian-Experiments/Jovian-NixOS/fd7753956149d4e8b19a810eed445d1a52aecd30' (2023-10-28)
  → 'git+file:///home/dre/Projects/Jovian-NixOS/' (2023-10-28)
error: builder for '/nix/store/v0bra4pq93bdm608ipnnv9803bh5821f-decky-loader-frontend-deps-2.10.5.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       > Progress: resolved 376, reused 354, downloaded 0, added 0
       > Progress: resolved 399, reused 377, downloaded 0, added 0
       > Progress: resolved 443, reused 421, downloaded 0, added 0
       > Progress: resolved 497, reused 475, downloaded 0, added 0
       > Progress: resolved 525, reused 503, downloaded 0, added 0
       >  ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '/fsevents/2.3.3' in pnpm-lock.yaml
       >
       > This issue is probably caused by a badly resolved merge conflict.
       > To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
       > Progress: resolved 525, reused 503, downloaded 0, added 0
       For full logs, run 'nix log /nix/store/v0bra4pq93bdm608ipnnv9803bh5821f-decky-loader-frontend-deps-2.10.5.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/k0k5465ymq5lcsjc4hhlxx2cbgbakv2l-decky-loader-frontend-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d4hms7fd3pbs5gcjf4qk48rsb1c1fnrr-decky-loader-2.10.5.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dgj5bx3wbdkhblzrppy14gvlq0vswiq0-unit-decky-loader.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zrln8nz7ri4yfl5gxsy64nx6yppq5b46-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gng86g8izvqpark718l03nc03fsvc0z0-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sz258ij3f1ad298909njdc6374c618nd-nixos-system-nix-deck-23.05.20231105.aeefe20.drv' failed to build

```

**Comment by imadnyc** [comment]
It finally builds if I update the decky-lib, and remove the `--node-linker=hoisted`. Does anyone know why this is enabled? The docs say that it should be disabled by default no? But it still doesn't show up in steam UI

**Comment by K900** [comment]
Tracked down to using NixOS 23.05 on Matrix, closing.
